resolves #1019 - added language to explicitly specify behavior when a vocab is known
json-schema-org/json-schema-spec pull request #1022
Opened 2020-11-19 04:50 UTC by gregsdennis

2020-11-19 14:05 UTC, Relequestual requested changes
Single change suggestion. Semantics! 🙄

Otherwise, this PR is good to go.
Thanks for your effort in making it happen =]

2020-11-19 14:05 UTC, Relequestual commented on jsonschema-core.xml
> +                        recognizes the vocabulary.
```suggestion
                        understands the vocabulary.
```

Recognising a vocabulary isn't the same as understanding it.

2020-11-19 18:23 UTC, gregsdennis commented
merge when ready

2020-11-20 17:10 UTC, karenetheridge commented
Is a footnote necessary, to indicate that the handling for the format vocabulary is special-cased?

2020-11-20 18:13 UTC, gregsdennis commented
@karenetheridge no.  Please see #1023 for changes to `format`, which remove the special-case treatment.  This change is purely for vocabularies.

2020-11-22 20:14 UTC, karenetheridge approved these changes

2020-11-22 22:00 UTC, Relequestual approved these changes

2020-11-22 22:04 UTC, merged