Add CREF about ambiguous behaviour of additionalProperties
json-schema-org/json-schema-spec pull request #1203
Opened 2022-03-30 08:49 UTC by Relequestual

Fixes #1172
Must see new issue relating to the behaviour of annotation collection for resolving in the next draft.
Related to https://github.com/json-schema-org/community/discussions/57

2022-04-03 16:27 UTC, karenetheridge requested changes

2022-04-03 16:27 UTC, karenetheridge commented on jsonschema-core.xml
> +                                but it does effect the resutling output format.
```suggestion
                                ambiguity in the output format. The ambiguity does not affect validation results,
                                but it does affect the resulting output format.
```

2022-04-03 16:27 UTC, karenetheridge commented on jsonschema-core.xml
> +                                and its use for validation purposes, but we also agreed not for this release.
```suggestion
                                and its use for validation purposes, but we also agreed not to do so for this release.
```

2022-04-03 16:27 UTC, karenetheridge commented on jsonschema-core.xml
> +                                The ambiguity allows for multiple valid output results depending on if annotations
```suggestion
                                The ambiguity allows for multiple valid output results depending on whether annotations
```

2022-04-03 16:27 UTC, karenetheridge commented on jsonschema-core.xml
> +                                however the previous interpritation is still valid.
```suggestion
                                It was proposed that we could read a different interpretation (https://github.com/json-schema-org/json-schema-spec/issues/1172#issuecomment-1049686478)
                                however the previous interpretation is still valid.
```

2022-04-08 15:08 UTC, Relequestual commented
I've removed some of the waffle from the CREF in the spec document as @jdesrosiers requested.
I've also added an Architectural Decision Record (ADR) for this overall decision to capture the reasoning behind it.
As you are named on the ADR (@karenetheridge @jdesrosiers @gregsdennis), it would be great to get your reviews.

Please feel free to make suggestion changes in your reviews if any additional thoughs come to mind or I've forgotten an option we considered.

2022-04-08 17:55 UTC, karenetheridge approved these changes
+1. Moving the decision content to an ADR is a good move as it allows more verbosity as well as linking to all the related issues where the discussions took place.

2022-04-11 00:10 UTC, jdesrosiers approved these changes
Looks good. Creating an ADR for this was a great idea! If we had one for when the annotation based behavior was was introduced, we could have saved ourselves a lot of speculation about what the intention was.

2022-04-11 00:10 UTC, jdesrosiers commented on adr/2022-04-08-cref-for-ambiguity-and-fix-later-gh-spec-issue-1172.md
> +Details with an example of the problem can be see in the Discussion's opening post specifically.
```suggestion
Details with an example of the problem can be seen in the Discussion's opening post specifically.
```

2022-04-13 19:50 UTC, gregsdennis approved these changes
Minor formatting issue. Good otherwise.

2022-04-13 19:50 UTC, gregsdennis commented on adr/2022-04-08-cref-for-ambiguity-and-fix-later-gh-spec-issue-1172.md
> +* [Pick one]()https://github.com/json-schema-org/community/discussions/57#discussioncomment-1416683) of the behaviours
Link formatting

2022-04-14 08:05 UTC, Relequestual commented
Rebased to remove commits for spelling and grammar fixes.

2022-04-14 08:05 UTC, merged