Replace defunct Travis CI integration with GitHub Actions
json-schema-org/json-schema-spec pull request #1266
Opened 2022-08-05 12:40 UTC by jviotti

The GitHub Actions setup is equivalent to the Travis CI configuration
with two differences:

- The GitHub Action setup does not set the `TAG` environment variable,
  as it didn't seem like `xml2rfc` would consume that at all (unless I'm
  missing something)

- The GitHub Action preserves the spec output (txt and html) as
  artifacts that can be downloaded after a successful run (to see the
  changes without having to locally render the specs)

Fixes: https://github.com/json-schema-org/json-schema-spec/issues/1262
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

2022-08-05 12:40 UTC, jviotti commented
@Relequestual I think you might need to enable the repository to run GitHub Actions from forks to be able to test this out. Once it is merged, we should also make this check required.

2022-08-05 13:48 UTC, gregsdennis commented
What I've had to do in `json-everything` is merge fork PRs into a secondary branch, just to get all of the actions to run properly (even when you get them running, they don't always have all the permissions they need).  Then I have another PR to pull into the primary branch.

2022-08-14 16:50 UTC, handrews approved these changes
Looks good to me.

2022-08-15 09:49 UTC, Relequestual commented
I believe this will also upload `requirements.txt` to the artifact bundle.

2022-08-15 09:50 UTC, Relequestual requested changes

2022-08-15 09:50 UTC, Relequestual commented on .github/workflows/ci.yml
> +          path: *.(html|txt)
```suggestion
          path: |
              *.(html|txt)
              !requirements.txt
```

2022-08-15 13:04 UTC, jviotti commented
Good catch @Relequestual ! Fixed.

2022-08-19 09:44 UTC, Relequestual approved these changes

2022-08-19 09:49 UTC, merged

2022-08-19 09:49 UTC, Relequestual commented
I decided to merge this immediatly as our current CI simply doesn't work.