Reverse "contains" <-> "minContains"/"maxContains" dependency
json-schema-org/json-schema-spec pull request #1312
Opened 2022-09-22 20:44 UTC by handrews

Fixes #1311.

2022-09-22 20:56 UTC, gregsdennis commented
I think this wording works, but do we want to have `minContains` & `maxContains` produce an annotation that is consumed by `contains`?  I understand the "missing keywords can't produce annotations" thing, but that's covered by the current language of assuming a min of 1.  Having this annotative communication maintains consistency with how other keywords work.

2022-09-22 21:20 UTC, handrews commented
@gregsdennis this wording was intended to specify the behavior in terms of annotations, and then note an alternative (which we do for some other keywords as well).  What are you looking for that isn't there?  Do you want more explicit discussion of the consumption of annotations in the description of "contains"?

2022-09-22 22:17 UTC, gregsdennis commented
I was thinking that `minContains` and `maxContains` would actively produce an annotation that would be consumed by `contains`.  This follows the model that we have established with `additional*` and `unevaluated*`.

Currently the wording you have for min/max doesn't say anything about annotations.  I think this needs to be added.

Essentially, the dependency is on the annotation rather than on the other keyword directly.

2022-09-23 01:31 UTC, handrews commented
@gregsdennis 

> Currently the wording you have for min/max doesn't say anything about annotations. I think this needs to be added.

Lines 2530 and 2544 say:

> The value of this keyword is used as its annotation result.

2022-09-23 01:37 UTC, gregsdennis commented
Okay, yeah.... I missed that.

2022-09-23 01:37 UTC, gregsdennis approved these changes

2022-09-23 02:01 UTC, handrews commented
@gregsdennis no worries, the mentions are very brief!  It actually took me a moment to find them again.

2022-09-26 23:16 UTC, jdesrosiers requested changes
Just one small typo, but otherwise looks good.

2022-09-26 23:16 UTC, jdesrosiers commented on jsonschema-core.xml
> +                            values that are valid against its subschema is with the inclusive range of
```suggestion
                            values that are valid against its subschema is within the inclusive range of
```

2022-09-26 23:22 UTC, jdesrosiers approved these changes

2022-10-08 19:43 UTC, handrews commented
The force-push just now was to rebase and (more importantly) credit @karenetheridge for first coming up with the idea in the commit log.

2022-10-08 19:44 UTC, merged