Issue-949: Fixing inconsistencies in output schema
json-schema-org/json-schema-spec pull request #950
Opened 2020-06-19 13:37 UTC by stan-sb

1. Changing "oneOf" to "anyOf", because basic, detailed and verbose have the same definition, oneOf would fail validation.
2. Adding "error" keyword and making either "error" or "errors" required in case "valid" is false.

2020-06-19 15:25 UTC, karenetheridge commented
There are some overlaps with #938 and #940.

2020-06-22 20:36 UTC, stan-sb commented
Looking at #938 and #940, these changes are distinct from both of them.

2020-06-22 20:40 UTC, karenetheridge commented
#940 also addresses oneOf -> anyOf.

2020-06-23 13:52 UTC, stan-sb commented
#940: Line #49: oneOf -> anyOf
#950: Line #6: oneOf -> anyOf

2020-09-04 16:45 UTC, handrews commented
@karenetheridge has @stan-sb addressed your concerns with his last comment?  I'd like to get a review from either you or @gregsdennis and get this merged if it is correct.

2020-09-26 19:32 UTC, handrews commented
@gregsdennis @karenetheridge any update on this?  I'd like to get it merged or rejected, whichever is appropriate.  We need to wrap up this draft and this has been open for 3 months now.

2020-09-26 23:12 UTC, gregsdennis commented
I have no strong feelings.  I had used `oneOf` because logically only one of the formats can be used.  But their schemas do overlap somewhat, so... sure.

2020-09-26 23:14 UTC, gregsdennis approved these changes

2020-09-26 23:15 UTC, gregsdennis requested changes

2020-09-26 23:15 UTC, gregsdennis commented on output/schema.json
> +            "oneOf": [
anyOf here, too.  Don't preclude having both.

2020-10-01 21:41 UTC, handrews commented on output/schema.json
> +            "oneOf": [
```suggestion
            "anyOf": [
```

2020-10-01 21:42 UTC, merged